### ISSUE TITLE
KNX messages duplicated after bridge runs for some time

### ISSUE THREAD

**Issue by giggo** [pakerfeldt/knx-mqtt-bridge#6]
After some time the bridge starts duplicating KNX message (and sending duplicated MQTT messages:
```

verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 2/1/14, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 2/1/14, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 2/1/14, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 2/1/14, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 2/1/14, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 2/1/14, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 2/1/14, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
verbose: 2019-01-31 22:42:43 **** KNX EVENT: GroupValue_Write, dst: 4/2/6, value: "false"
```

My config.yaml is:
```
# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'debug'
# One of value-only, full
#    value-only - converts any known group addresses to its value
#    full - a json object containing value. Additionally also name and unit type for known group addresses.
#messageType: value-only
messageType: value-only
# Ignore unknown group addresses
ignoreUnknownGroupAddresses: false
knx:
    # ETS exported group addresses
    # etsExport: '/home/pi/knx-mqtt-bridge/knx_master.xml'
    etsExport: '/home/pi/knx-mqtt-bridge/gruppenadressenets5modified.xml'
    #etsExport: '/home/pi/knx-mqtt-bridge/sterntaler.knxproj'
    # Configuration passed to the KNX library
    options:
    ipAddr: '192.168.1.13'
    ipPort: 3671
    forceTunneling: true
    physAddr: '2.1.11'
    minimumDelay: 200
    suppress_ack_ldatareq: true

mqtt:
    # URL to MQTT broker
    url: 'mqtt://localhost'
    # Configuration passed to the MQTT library
    options:
        username: 'mqtt_username'
        password: 'mqtt_password'
    # Prefix to mqtt topic
    topicPrefix: 'knx'

```
The longer the bridge runs the more duplicates I get. I tried to increase the minimumDelay to more than 1s without a difference.

My KNX packet sniffer does not show these duplicates

Any idea why?
